language: d
d:
  - dmd
  - dmd-2.075.0
  - ldc

script:
  $DMD -g -of=thread_pool src/mmutils/thread_pool.d && ./thread_pool

jobs:
  build:
    steps:
      - checkout
      - run: $DMD -g -of=thread_pool src/mmutils/thread_pool.d
  test:
    requires:
      - build
    steps:
      - run: ./thread_pool

workflows:
  version: 2
  commit:
    jobs:
      - test