language: d
d:
  - dmd
  - dmd-2.075.0
  - ldc

script:
  $DMD -g -of=thread_pool src/mmutils/thread_pool.d && ./thread_pool && dub build -b ddox

deploy:
  local_dir: ./docs
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master