version: 2
jobs:
  build:
    docker:
      - image: dlang2/dmd-circleci
    steps:
      - checkout
      - run: dmd -g -of=thread_pool src/mmutils/thread_pool.d && ./thread_pool
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
